version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  api:
    build: ./pagamentos/pagamentos
    ports:
      - "8080:8080"

  frontend:
    build: ./front
    ports:
      - "4200:80"
    depends_on:
      - api
